# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "wayland-extend"
BBFILE_PATTERN_wayland-extend = "^${LAYERDIR}/"
BBFILE_PRIORITY_wayland-extend = "6"
LAYERSERIES_COMPAT_wayland-extend = "scarthgap"

LAYERDEPENDS_wayland-extend = "core yocto yoctobsp openembedded-layer meta-python networking-layer"
